stages:
  - test
  - deploy

variables:
  AWS_SECRET_ACCESS_KEY: 6e7459d422b6db71a74d8f59ace117ece1a796ff
  AWS_ACCESS_KEY_ID: 5039ad0ac62c23b27933464209ca72e2d4a04a2b
  SECRET_TOKEN: 1ae7116d-44bf-4157-a7e1-18d3f5b04b3b

test:
  stage: test
  script:
    - echo 'Running tests...'

deploy:
  stage: deploy
  script:
    - echo 'Deploying...'
